/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StockMaster;

import conexionesSQL.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class altaArticulos extends javax.swing.JFrame {

    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();

    /**
     * Creates new form usuarios
     */
    public altaArticulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconoUser = new javax.swing.JLabel();
        btnArticulos = new javax.swing.JLabel();
        btnArticulosFondo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JLabel();
        textPrecioPublico = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        textStock = new javax.swing.JLabel();
        textPrecioDistribuidor = new javax.swing.JLabel();
        precioPublico = new javax.swing.JTextField();
        precioDistribuidor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 470));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-full-image-96.png"))); // NOI18N
        jPanel1.add(iconoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btnArticulos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnArticulos.setForeground(new java.awt.Color(255, 255, 255));
        btnArticulos.setText("Crear Articulo");
        btnArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArticulosMouseClicked(evt);
            }
        });
        jPanel1.add(btnArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 448, 100, 30));
        btnArticulos.getAccessibleContext().setAccessibleName("Añadir usuario");

        btnArticulosFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RectánguloAzulpeque.png"))); // NOI18N
        jPanel1.add(btnArticulosFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.setText("Nombre:");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        Nombre.setForeground(new java.awt.Color(51, 51, 51));
        Nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Nombre.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 230, 20));

        txtDescripcion.setForeground(new java.awt.Color(51, 51, 51));
        txtDescripcion.setText("Descripción");
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        textPrecioPublico.setForeground(new java.awt.Color(51, 51, 51));
        textPrecioPublico.setText("Precio Publico:");
        jPanel1.add(textPrecioPublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        stock.setForeground(new java.awt.Color(51, 51, 51));
        stock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stock.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 250, 20));

        textStock.setForeground(new java.awt.Color(51, 51, 51));
        textStock.setText("Stock:");
        jPanel1.add(textStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        textPrecioDistribuidor.setForeground(new java.awt.Color(51, 51, 51));
        textPrecioDistribuidor.setText("Precio Distribuidor:");
        jPanel1.add(textPrecioDistribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        precioPublico.setForeground(new java.awt.Color(51, 51, 51));
        precioPublico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        precioPublico.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(precioPublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 220, 20));

        precioDistribuidor.setForeground(new java.awt.Color(51, 51, 51));
        precioDistribuidor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        precioDistribuidor.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(precioDistribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 200, 20));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        descripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(descripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 290, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void insertarDatos() {

        try {
            String SQL = "INSERT into item (nombre,descripcion,precio_publico,precio_distribuidor,stock) values (?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setString(1, Nombre.getText());
            pst.setString(2, descripcion.getText());
            pst.setInt(3, Integer.parseInt(precioPublico.getText()));
            pst.setInt(4, Integer.parseInt(precioDistribuidor.getText()));
            pst.setInt(5, Integer.parseInt(stock.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(null, "Cambios guardados correctamente");
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error, no se realizaron cambios. Favor de verificar los datos");
            System.out.println("Error" + e);
        }

    }

    private void btnArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticulosMouseClicked
        if (Nombre.getText().equals("") | stock.getText().equals("") | descripcion.getText().equals("") | precioPublico.getText().equals("") | precioDistribuidor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Para continuar debe rellenar todos los campos", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            int result = JOptionPane.showConfirmDialog(null, " ¿Está seguro que desea realizar los cambios? ", "",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                insertarDatos();
                this.dispose();

            }

        }


    }//GEN-LAST:event_btnArticulosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void altaUsuarios() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new altaArticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel btnArticulos;
    private javax.swing.JLabel btnArticulosFondo;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel iconoUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField precioDistribuidor;
    private javax.swing.JTextField precioPublico;
    private javax.swing.JTextField stock;
    private javax.swing.JLabel textPrecioDistribuidor;
    private javax.swing.JLabel textPrecioPublico;
    private javax.swing.JLabel textStock;
    private javax.swing.JLabel txtDescripcion;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables

}
