/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StockMaster;

import conexionesSQL.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class altaUsuarios extends javax.swing.JFrame {

    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();

    /**
     * Creates new form usuarios
     */
    public altaUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconoUser = new javax.swing.JLabel();
        btnArticulos = new javax.swing.JLabel();
        btnArticulosFondo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        textContrasena = new javax.swing.JLabel();
        textID = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        textPuesto = new javax.swing.JLabel();
        puesto = new javax.swing.JComboBox<>();
        Confirmarcontrasenia = new javax.swing.JPasswordField();
        textConfirmarContrasena = new javax.swing.JLabel();
        contrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 470));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-male-user-96.png"))); // NOI18N
        jPanel1.add(iconoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        btnArticulos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnArticulos.setForeground(new java.awt.Color(255, 255, 255));
        btnArticulos.setText("Crear usuario");
        btnArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArticulosMouseClicked(evt);
            }
        });
        jPanel1.add(btnArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 398, 100, 30));
        btnArticulos.getAccessibleContext().setAccessibleName("Añadir usuario");

        btnArticulosFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RectánguloAzulpeque.png"))); // NOI18N
        jPanel1.add(btnArticulosFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.setText("Nombre:");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        Nombre.setForeground(new java.awt.Color(51, 51, 51));
        Nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Nombre.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 220, 20));

        txtApellidos.setForeground(new java.awt.Color(51, 51, 51));
        txtApellidos.setText("Apellidos:");
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        apellidos.setForeground(new java.awt.Color(51, 51, 51));
        apellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        apellidos.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 186, 220, 20));

        textContrasena.setForeground(new java.awt.Color(51, 51, 51));
        textContrasena.setText("Contraseña:");
        jPanel1.add(textContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        textID.setForeground(new java.awt.Color(51, 51, 51));
        textID.setText("ID:");
        jPanel1.add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        ID.setForeground(new java.awt.Color(51, 51, 51));
        ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ID.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 227, 260, 20));

        textPuesto.setForeground(new java.awt.Color(51, 51, 51));
        textPuesto.setText("Puesto:");
        jPanel1.add(textPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado", " " }));
        jPanel1.add(puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 240, -1));

        Confirmarcontrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Confirmarcontrasenia.setMinimumSize(new java.awt.Dimension(6, 16));
        jPanel1.add(Confirmarcontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 316, 160, 20));

        textConfirmarContrasena.setForeground(new java.awt.Color(51, 51, 51));
        textConfirmarContrasena.setText("Confirmar Contraseña:");
        jPanel1.add(textConfirmarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        contrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contrasenia.setMinimumSize(new java.awt.Dimension(6, 16));
        jPanel1.add(contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 277, 210, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void insertarDatos() {

        try {
            String SQL = "INSERT into user (iduser,Nombre,apellidos,puesto,password) values (?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setString(1, ID.getText());
            pst.setString(2, Nombre.getText());
            pst.setString(3, apellidos.getText());
            int seleccionPuesto = puesto.getSelectedIndex();
            pst.setString(4, puesto.getItemAt(seleccionPuesto));
            String pass = String.valueOf(contrasenia.getPassword());
            pst.setString(5, pass);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Cambios guardados correctamente");
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error, no se realizaron cambios. Favor de verificar los datos");
            System.out.println("Error" + e);
        }

    }

    private void btnArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticulosMouseClicked
        if (Nombre.getText().equals("") | ID.getText().equals("") | apellidos.getText().equals("") | contrasenia.getText().equals("") | Confirmarcontrasenia.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Para continuar debe rellenar todos los campos", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {

            if (contrasenia.getText().equals(Confirmarcontrasenia.getText())) {
                int result = JOptionPane.showConfirmDialog(null, " ¿Está seguro que desea realizar los cambios? ", "",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    insertarDatos();
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Alerta", JOptionPane.WARNING_MESSAGE);
            }

        }


    }//GEN-LAST:event_btnArticulosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void altaUsuarios() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new altaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Confirmarcontrasenia;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField apellidos;
    private javax.swing.JLabel btnArticulos;
    private javax.swing.JLabel btnArticulosFondo;
    private javax.swing.JPasswordField contrasenia;
    private javax.swing.JLabel iconoUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> puesto;
    private javax.swing.JLabel textConfirmarContrasena;
    private javax.swing.JLabel textContrasena;
    private javax.swing.JLabel textID;
    private javax.swing.JLabel textPuesto;
    private javax.swing.JLabel txtApellidos;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables

}
