/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StockMaster;

import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import conexionesSQL.conexionSQL;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import static seguricaminventario.notaVenta.IDVenta;

/**
 *
 * @author Aleja
 */
public class reportes extends javax.swing.JFrame {

    public static String destino = "C:\\reporte.pdf";
    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();
    public static String IDVenta;

    /**
     * Creates new form reportes
     */
    public reportes() throws FileNotFoundException {
        initComponents();
        seleccionReporte();

    }

    public static String getIDVenta() {
        return IDVenta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottonGroupTipodeReporte = new javax.swing.ButtonGroup();
        panelArticulos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArticulos = new javax.swing.JTable();
        panelVentas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        btnReporteVentas = new javax.swing.JRadioButton();
        btnReporteArticulos = new javax.swing.JRadioButton();
        btnGenerarPDF = new javax.swing.JButton();
        txtTipoReporte = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 380));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaArticulos.getTableHeader().setReorderingAllowed(false);
        tablaArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaArticulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaArticulos);

        javax.swing.GroupLayout panelArticulosLayout = new javax.swing.GroupLayout(panelArticulos);
        panelArticulos.setLayout(panelArticulosLayout);
        panelArticulosLayout.setHorizontalGroup(
            panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelArticulosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        panelArticulosLayout.setVerticalGroup(
            panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(panelArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelArticulosLayout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        getContentPane().add(panelArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 250));

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablaVentas.getTableHeader().setReorderingAllowed(false);
        tablaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVentasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaVentas);

        javax.swing.GroupLayout panelVentasLayout = new javax.swing.GroupLayout(panelVentas);
        panelVentas.setLayout(panelVentasLayout);
        panelVentasLayout.setHorizontalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelVentasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        panelVentasLayout.setVerticalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelVentasLayout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        getContentPane().add(panelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 250));

        bottonGroupTipodeReporte.add(btnReporteVentas);
        btnReporteVentas.setSelected(true);
        btnReporteVentas.setText("Ventas");
        btnReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporteVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 7, -1, -1));

        bottonGroupTipodeReporte.add(btnReporteArticulos);
        btnReporteArticulos.setText("Articulos");
        btnReporteArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteArticulosActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporteArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 7, -1, -1));

        btnGenerarPDF.setText("Generar PDF");
        btnGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPDFActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 294, -1, -1));

        txtTipoReporte.setText("Tipo de reporte");
        getContentPane().add(txtTipoReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPDFActionPerformed

        JFileChooser selectorCarpeta = new JFileChooser();

        selectorCarpeta.setDialogTitle("Seleccione la carpeta para guardar el reporte");
        selectorCarpeta.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        selectorCarpeta.setAcceptAllFileFilterUsed(false);
        int seleccion = selectorCarpeta.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {

            File carpetaSelecionada = selectorCarpeta.getSelectedFile();

            Date date = new Date();
            DateFormat hourdateFormat = new SimpleDateFormat("HH.mm.ss dd-MM-yyyy");
            String historial = hourdateFormat.format(date);

            destino = carpetaSelecionada.toString() + "\\REPORTE " + historial + ".pdf";
            JOptionPane.showMessageDialog(this, "El reporte se guardo en " + carpetaSelecionada.toString());
            try {
                generarPDF();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(reportes.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "No se guardo ningun reporte");
        }


    }//GEN-LAST:event_btnGenerarPDFActionPerformed

    private void btnReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteVentasActionPerformed
        seleccionReporte();
    }//GEN-LAST:event_btnReporteVentasActionPerformed

    private void btnReporteArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteArticulosActionPerformed
        seleccionReporte();
    }//GEN-LAST:event_btnReporteArticulosActionPerformed

    private void tablaArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaArticulosMouseClicked

    }//GEN-LAST:event_tablaArticulosMouseClicked

    private void tablaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVentasMouseClicked

        if (evt.getClickCount() > 1) {

            IDVenta = tablaVentas.getValueAt(tablaVentas.getSelectedRow(), 0).toString();
            notaVenta ventanaNotaVenta = new notaVenta();
            ventanaNotaVenta.setVisible(true);

        }


    }//GEN-LAST:event_tablaVentasMouseClicked

    public void mostrarDatosArticulos() {

        String[] titulos = {"ID", "Articulo", "P. Publico", "P. Distribuidor", "Stock"};
        String[] registros = new String[5];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String SQL = "select * from item";

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            while (rs.next()) {

                registros[0] = rs.getString("iditem");
                registros[1] = rs.getString("nombre");
                registros[2] = rs.getString("precio_publico");
                registros[3] = rs.getString("precio_distribuidor");
                registros[4] = rs.getString("stock");

                modelo.addRow(registros);

            }

            tablaArticulos.setModel(modelo);
            tablaArticulos.setDefaultEditor(Object.class, null);
            establecerColumnas();
        } catch (Exception e) {
            System.out.println("Error" + e);

        }

    }

    public void mostrarDatosVentas() {

        String[] titulos = {"ID", "Fecha", "Total", "Vendedor"};
        String[] registros = new String[4];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String SQL = "select * from venta";

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            while (rs.next()) {

                registros[0] = rs.getString("idventa");
                registros[1] = rs.getString("fecha");
                registros[2] = rs.getString("total");
                String idusuario = rs.getString("user_iduser");

                String SQL2 = "select * from user where iduser = '" + idusuario + "'";
                Statement st2 = con.createStatement();
                ResultSet rs2 = st2.executeQuery(SQL2);
                while (rs2.next()) {
                    registros[3] = rs2.getString("nombre") + " " + rs2.getString("apellidos");
                }

                modelo.addRow(registros);

            }

            tablaVentas.setModel(modelo);
            tablaVentas.setDefaultEditor(Object.class, null);
            establecerColumnas();
        } catch (Exception e) {
            System.out.println("Error" + e);

        }

    }

    public void generarPDF() throws FileNotFoundException {

        String SQL = "select * from item";

        PdfWriter writer = new PdfWriter(destino);
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf, PageSize.A4);
        Table table = new Table(new float[]{1, 6, 1, 1, 1});
        table.setWidth(500);

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            table.addHeaderCell(new Cell().add(new Paragraph("ID")));
            table.addHeaderCell(new Cell().add(new Paragraph("Articulo")));
            table.addHeaderCell(new Cell().add(new Paragraph("Precio Publico")));
            table.addHeaderCell(new Cell().add(new Paragraph("Precio Distribuidor")));
            table.addHeaderCell(new Cell().add(new Paragraph("Stock")));
            while (rs.next()) {

                table.addCell(new Cell().add(new Paragraph(rs.getString("iditem"))));
                table.addCell(new Cell().add(new Paragraph(rs.getString("nombre"))));
                table.addCell(new Cell().add(new Paragraph(rs.getString("precio_publico"))));
                table.addCell(new Cell().add(new Paragraph(rs.getString("precio_distribuidor"))));
                table.addCell(new Cell().add(new Paragraph(rs.getString("stock"))));
            }

            document.add(table);
            document.close();
            establecerColumnas();
        } catch (Exception e) {
            System.out.println("Error" + e);

        }

    }

    public void establecerColumnas() {

        tablaArticulos.getColumnModel().getColumn(0).setPreferredWidth(25);
        tablaArticulos.getColumnModel().getColumn(1).setPreferredWidth(250);
        tablaArticulos.getColumnModel().getColumn(2).setPreferredWidth(50);
        tablaArticulos.getColumnModel().getColumn(3).setPreferredWidth(50);
        tablaArticulos.getColumnModel().getColumn(4).setPreferredWidth(25);
    }

    public void seleccionReporte() {

        if (btnReporteVentas.isSelected()) {
            panelVentas.setVisible(true);
            panelArticulos.setVisible(false);
            btnGenerarPDF.setVisible(false);
            mostrarDatosVentas();
        }
        if (btnReporteArticulos.isSelected()) {
            panelVentas.setVisible(false);
            panelArticulos.setVisible(true);
            btnGenerarPDF.setVisible(true);
            mostrarDatosArticulos();

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new reportes().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bottonGroupTipodeReporte;
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JRadioButton btnReporteArticulos;
    private javax.swing.JRadioButton btnReporteVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelArticulos;
    private javax.swing.JPanel panelVentas;
    private javax.swing.JTable tablaArticulos;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JLabel txtTipoReporte;
    // End of variables declaration//GEN-END:variables
}
