/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StockMaster;

import conexionesSQL.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleja
 */
public class tipoDeVenta extends javax.swing.JFrame {

    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();
    ventanaPrincipal datosArticulo = new ventanaPrincipal();
    float precioVentaPublico = 0, precioVentaDistribuidor = 0, totalArticulos = 0;
    int cantidadStock;
    String tipodeVenta;
 
    /**
     * Creates new form tipoDeVenta
     */
    public tipoDeVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTipoVenta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnAñadir = new javax.swing.JButton();
        TxtArticulo = new javax.swing.JLabel();
        txtTipodeVenta = new javax.swing.JLabel();
        btnprecioPublico = new javax.swing.JRadioButton();
        btnPrecioDistribuidor = new javax.swing.JRadioButton();
        txtCantidad = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(320, 230));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAñadir.setText("Añadir al carrito");
        btnAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        TxtArticulo.setText("Artículo");
        jPanel1.add(TxtArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 230, 10));

        txtTipodeVenta.setText("Tipo de venta:");
        jPanel1.add(txtTipodeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 65, -1, -1));

        btnTipoVenta.add(btnprecioPublico);
        btnprecioPublico.setSelected(true);
        btnprecioPublico.setText("Publicio");
        btnprecioPublico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprecioPublicoActionPerformed(evt);
            }
        });
        jPanel1.add(btnprecioPublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        btnTipoVenta.add(btnPrecioDistribuidor);
        btnPrecioDistribuidor.setText("Distribuidor");
        btnPrecioDistribuidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecioDistribuidorActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrecioDistribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        txtCantidad.setText("Cantidad: ");
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidadKeyReleased(evt);
            }
        });
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 97, 40, -1));

        total.setText("Total a pagar $ ");
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        if (totalArticulos > 0) {
            int result = JOptionPane.showConfirmDialog(null, " ¿Está seguro que desea agregar los artículos? ", "",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                insertarDatos();
                JOptionPane.showMessageDialog(null, "Cambios guardados correctamente");  
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tienes que ingresar una cantidad");
        }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnPrecioDistribuidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecioDistribuidorActionPerformed
        calcularCosto();

    }//GEN-LAST:event_btnPrecioDistribuidorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          mostrarDatos2(datosArticulo.getIDArticulo());
    }//GEN-LAST:event_formWindowOpened

    private void cantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyReleased
        calcularCosto();
    }//GEN-LAST:event_cantidadKeyReleased

    private void btnprecioPublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprecioPublicoActionPerformed
        calcularCosto();
    }//GEN-LAST:event_btnprecioPublicoActionPerformed

    public void calcularCosto() {

        try {

            int numeroCantidad = Integer.parseInt(cantidad.getText());
            if (numeroCantidad > 0) {
                if (numeroCantidad <= cantidadStock) {
                    if (btnPrecioDistribuidor.isSelected()) {
                        totalArticulos = Integer.parseInt(cantidad.getText()) * precioVentaDistribuidor;
                        total.setText("Total a pagar $ " + Float.toString(totalArticulos));
                        tipodeVenta="Distribuidor";
                    }
                    if (btnprecioPublico.isSelected()) {
                        totalArticulos = Integer.parseInt(cantidad.getText()) * precioVentaPublico;
                        total.setText("Total a pagar $ " + Float.toString(totalArticulos));
                        tipodeVenta="Publico";
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Favor de ingresar una cantidad inferior a " + cantidadStock);
                    cantidad.setText("");
                    total.setText("");
                    totalArticulos = 0;

                }

            } else {
                cantidad.setText("");
                total.setText("");
                totalArticulos = 0;
            }
        } catch (NumberFormatException nfe) {
            cantidad.setText("");
            total.setText("");
            totalArticulos = 0;

        }
    }

    public void mostrarDatos2(String identificador) {

        
        String SQL = "select * from item where iditem = '" + identificador + "'";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            while (rs.next()) {
                TxtArticulo.setText(rs.getString("nombre"));
                txtCantidad.setText("Cantidad (" + rs.getString("stock") + ") ");
                cantidadStock = Integer.parseInt(rs.getString("stock"));
                precioVentaDistribuidor = rs.getInt("precio_distribuidor");
                precioVentaPublico = rs.getInt("precio_publico");

            }

        } catch (Exception e) {
            System.out.println("Error" + e);

        }

    }
    
        public void insertarDatos() {

        try {
            String SQL = "INSERT into articulo_lista (idarticuloLista,cantidad,precio,tipoVenta) values (?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(SQL);
            
            pst.setString(1, datosArticulo.getIDArticulo());
            pst.setInt(2, Integer.parseInt(cantidad.getText()));
            pst.setFloat(3, totalArticulos);
            pst.setString(4, tipodeVenta);            
            pst.execute();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error, no se realizaron cambios. Favor de verificar los datos");
            System.out.println("Error" + e);
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void tipoDeVenta() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tipoDeVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tipoDeVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tipoDeVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tipoDeVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tipoDeVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TxtArticulo;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JRadioButton btnPrecioDistribuidor;
    private javax.swing.ButtonGroup btnTipoVenta;
    private javax.swing.JRadioButton btnprecioPublico;
    private javax.swing.JTextField cantidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel total;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JLabel txtTipodeVenta;
    // End of variables declaration//GEN-END:variables
}
