/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StockMaster;

import conexionesSQL.conexionSQL;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aleja
 */
public class ventanaUsuarios extends javax.swing.JFrame {

    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();
    login datosUsuario = new login();
    
    /**
     * Creates new form inicioAdministrador
     */
    public ventanaUsuarios() {
        initComponents();
        mostrarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        Nombre = new javax.swing.JTextField();
        txtNombre = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        textID = new javax.swing.JLabel();
        puestoText = new javax.swing.JTextField();
        puesto = new javax.swing.JComboBox<>();
        textPuesto = new javax.swing.JLabel();
        cambiarContrasena = new javax.swing.JCheckBox();
        contrasena = new javax.swing.JPasswordField();
        textContrasena = new javax.swing.JLabel();
        confirmarContrasena = new javax.swing.JPasswordField();
        textCofirmarContrasena = new javax.swing.JLabel();
        btnBusqueda = new javax.swing.JLabel();
        barraBusqueda = new javax.swing.JTextField();
        fondoBarraBusqueda = new javax.swing.JLabel();
        imgUsuario = new javax.swing.JLabel();
        fondoImgUsuario = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        fondoEditar = new javax.swing.JLabel();
        btnGuardarPassword = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        fondoGuardar = new javax.swing.JLabel();
        imgCuadroAzul = new javax.swing.JLabel();
        imgLogoSeguricam = new javax.swing.JLabel();
        mensajeBienvenida = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JLabel();
        btnUsuariosFondo = new javax.swing.JLabel();
        btnVentas = new javax.swing.JLabel();
        btnVentasFondo = new javax.swing.JLabel();
        btnArticulos = new javax.swing.JLabel();
        btnArticulosFondo = new javax.swing.JLabel();
        fondoBlanco = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();
        fondoCerrarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(942, 650));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1170, 630));
        jPanel1.setMinimumSize(new java.awt.Dimension(1170, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1170, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 560, -1));

        Nombre.setEditable(false);
        Nombre.setBackground(new java.awt.Color(5, 86, 172));
        Nombre.setForeground(new java.awt.Color(51, 51, 51));
        Nombre.setBorder(null);
        Nombre.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 170, 20));

        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setText("Nombre:");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));

        apellidos.setEditable(false);
        apellidos.setBackground(new java.awt.Color(5, 86, 172));
        apellidos.setForeground(new java.awt.Color(51, 51, 51));
        apellidos.setBorder(null);
        apellidos.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 170, 20));

        txtApellidos.setForeground(new java.awt.Color(255, 255, 255));
        txtApellidos.setText("Apellidos:");
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));

        ID.setEditable(false);
        ID.setBackground(new java.awt.Color(5, 86, 172));
        ID.setForeground(new java.awt.Color(51, 51, 51));
        ID.setBorder(null);
        ID.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        ID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDMouseClicked(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 200, 20));

        textID.setForeground(new java.awt.Color(255, 255, 255));
        textID.setText("ID:");
        jPanel1.add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));

        puestoText.setEditable(false);
        puestoText.setBackground(new java.awt.Color(5, 86, 172));
        puestoText.setForeground(new java.awt.Color(51, 51, 51));
        puestoText.setBorder(null);
        puestoText.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(puestoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 200, 20));

        puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado", " " }));
        puesto.setEnabled(false);
        jPanel1.add(puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 130, -1));

        textPuesto.setForeground(new java.awt.Color(255, 255, 255));
        textPuesto.setText("Puesto:");
        jPanel1.add(textPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, -1, -1));

        cambiarContrasena.setBackground(new java.awt.Color(5, 86, 172));
        cambiarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        cambiarContrasena.setText("Cambiar contraseña");
        cambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(cambiarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 170, -1));

        contrasena.setBackground(new java.awt.Color(5, 86, 172));
        contrasena.setForeground(new java.awt.Color(255, 255, 255));
        contrasena.setText("jPasswordField1");
        contrasena.setBorder(null);
        contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contrasenaMouseClicked(evt);
            }
        });
        jPanel1.add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, -1, -1));

        textContrasena.setForeground(new java.awt.Color(255, 255, 255));
        textContrasena.setText("Contraseña:");
        jPanel1.add(textContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, -1));

        confirmarContrasena.setBackground(new java.awt.Color(5, 86, 172));
        confirmarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        confirmarContrasena.setText("jPasswordField1");
        confirmarContrasena.setBorder(null);
        jPanel1.add(confirmarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));

        textCofirmarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        textCofirmarContrasena.setText("Confirmar contraseña:");
        jPanel1.add(textCofirmarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));

        btnBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-search-more-96.png"))); // NOI18N
        btnBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnBusquedaKeyTyped(evt);
            }
        });
        jPanel1.add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 95, -1, -1));

        barraBusqueda.setBackground(new java.awt.Color(162, 162, 162));
        barraBusqueda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        barraBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        barraBusqueda.setText("Búsqueda de usuario: ");
        barraBusqueda.setBorder(null);
        barraBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraBusquedaMouseClicked(evt);
            }
        });
        barraBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraBusquedaActionPerformed(evt);
            }
        });
        barraBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barraBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                barraBusquedaKeyTyped(evt);
            }
        });
        jPanel1.add(barraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 340, 30));

        fondoBarraBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barrabusqueda2.png"))); // NOI18N
        jPanel1.add(fondoBarraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        imgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-male-user-96.png"))); // NOI18N
        jPanel1.add(imgUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        fondoImgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rectángulo 12.png"))); // NOI18N
        jPanel1.add(fondoImgUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 555, -1, -1));

        fondoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rectángulo -1.png"))); // NOI18N
        jPanel1.add(fondoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, -1, -1));

        btnGuardarPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarPassword.setText("Guardar");
        btnGuardarPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(btnGuardarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 555, -1, -1));

        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 555, -1, -1));

        fondoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rectángulo -1c.png"))); // NOI18N
        jPanel1.add(fondoGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, -1, -1));

        imgCuadroAzul.setBackground(new java.awt.Color(5, 86, 172));
        imgCuadroAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rectángulo 9b.png"))); // NOI18N
        jPanel1.add(imgCuadroAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        imgLogoSeguricam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopeque.png"))); // NOI18N
        jPanel1.add(imgLogoSeguricam, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        mensajeBienvenida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mensajeBienvenida.setForeground(new java.awt.Color(102, 102, 102));
        mensajeBienvenida.setText("Te damos la bienvendida + nombreUsuario");
        jPanel1.add(mensajeBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 370, 30));

        btnUsuarios.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Añadir usuario");
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
        });
        jPanel1.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 88, 70, 30));

        btnUsuariosFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RectánguloAzul.png"))); // NOI18N
        jPanel1.add(btnUsuariosFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        btnVentas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setText("Reportes");
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasMouseClicked(evt);
            }
        });
        jPanel1.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 88, 70, 30));

        btnVentasFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RectánguloAzulClaropeque.png"))); // NOI18N
        jPanel1.add(btnVentasFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        btnArticulos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnArticulos.setForeground(new java.awt.Color(255, 255, 255));
        btnArticulos.setText("Articulos");
        btnArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArticulosMouseClicked(evt);
            }
        });
        jPanel1.add(btnArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 88, 100, 30));

        btnArticulosFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RectánguloAzulClaro.png"))); // NOI18N
        jPanel1.add(btnArticulosFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        fondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RectanguloBlanco3.png"))); // NOI18N
        jPanel1.add(fondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 870, -1));

        btnCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 585, -1, 20));

        fondoCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Grupo 22.png"))); // NOI18N
        jPanel1.add(fondoCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        int result = JOptionPane.showConfirmDialog(null, " ¿Está seguro que desea cerrar la sesión? ", "",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {

            login ventanaLogin = new login();
            this.dispose();
            ventanaLogin.setVisible(true);

        }
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        mensajeBienvenida.setText("Te damos la bienvenida, "+datosUsuario.getNombreUsuario()+" "+datosUsuario.getApellidosUsuario());
        imgLogoSeguricam.requestFocus();
        fondoGuardar.setVisible(false);
        btnGuardar.setVisible(false);
        puesto.setVisible(false);
        contrasena.setVisible(false);
        textContrasena.setVisible(false);
        confirmarContrasena.setVisible(false);
        textCofirmarContrasena.setVisible(false);
        cambiarContrasena.setVisible(false);
        btnGuardarPassword.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        Nombre.setEditable(true);
        Nombre.setBackground(Color.WHITE);
        apellidos.setEditable(true);
        apellidos.setBackground(Color.WHITE);
        //ID.setEditable(true);
        ID.setBackground(Color.WHITE);
        puestoText.setVisible(false);
        puesto.setVisible(true);
        puesto.setEnabled(true);
        puesto.setBackground(Color.WHITE);
        fondoGuardar.setVisible(true);
        btnGuardar.setVisible(true);
        cambiarContrasena.setVisible(true);
        if (tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 3).toString().equals("Administrador")) {
            System.out.println("es admin");
            puesto.setSelectedIndex(0);
        } else {
            puesto.setSelectedIndex(1);
            System.out.println("Es empleado");
        }


    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        
        if (Nombre.getText().equals("") | ID.getText().equals("") | apellidos.getText().equals("") | contrasena.getText().equals("") | confirmarContrasena.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Para continuar debe rellenar todos los campos", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {

            int result = JOptionPane.showConfirmDialog(null, " ¿Está seguro que desea realizar los cambios? ", "",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {

                Nombre.setEditable(false);
                Nombre.setBackground(new java.awt.Color(5, 86, 172));
                apellidos.setEditable(false);
                apellidos.setBackground(new java.awt.Color(5, 86, 172));
                ID.setEditable(false);
                ID.setBackground(new java.awt.Color(5, 86, 172));
                puesto.setEnabled(false);
                puesto.setBackground(new java.awt.Color(5, 86, 172));
                puesto.setVisible(false);
                puestoText.setVisible(true);

                fondoGuardar.setVisible(false);
                btnGuardar.setVisible(false);

                actualizarDatos();
                mostrarDatos();

            }

        }


    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticulosMouseClicked
        ventanaPrincipal ventanaInicioAdministrador = new ventanaPrincipal();
        ventanaInicioAdministrador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnArticulosMouseClicked

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        altaUsuarios ventanaAltaUsuarios = new altaUsuarios();
        ventanaAltaUsuarios.setVisible(true);
    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        ID.setText(tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 0).toString());
        Nombre.setText(tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 1).toString());
        apellidos.setText(tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 2).toString());
        puestoText.setText(tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 3).toString());
        if (tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 3).toString().equals("Administrador")) {
            puesto.setSelectedIndex(0);
        } else {
            puesto.setSelectedIndex(1);
        }

    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void IDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDMouseClicked
        JOptionPane.showMessageDialog(null, "El ID no se puede editar");
    }//GEN-LAST:event_IDMouseClicked

    private void cambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContrasenaActionPerformed
        if (cambiarContrasena.isSelected()) {
            contrasena.setVisible(true);
            textContrasena.setVisible(true);
            confirmarContrasena.setVisible(true);
            textCofirmarContrasena.setVisible(true);
            btnGuardar.setVisible(false);
            btnGuardarPassword.setVisible(true);
            fondoGuardar.setVisible(true);

        } else {
            contrasena.setVisible(false);
            textContrasena.setVisible(false);
            confirmarContrasena.setVisible(false);
            textCofirmarContrasena.setVisible(false);
        }
    }//GEN-LAST:event_cambiarContrasenaActionPerformed

    private void contrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenaMouseClicked
        contrasena.setText("");
        confirmarContrasena.setText("");
    }//GEN-LAST:event_contrasenaMouseClicked

    private void btnGuardarPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarPasswordMouseClicked

        if (Nombre.getText().equals("") | ID.getText().equals("") | apellidos.getText().equals("") | contrasena.getText().equals("") | confirmarContrasena.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Para continuar debe rellenar todos los campos", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {

            if (contrasena.getText().equals(confirmarContrasena.getText())) {
                int result = JOptionPane.showConfirmDialog(null, " ¿Está seguro que desea realizar los cambios? ", "",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {

                    Nombre.setEditable(false);
                    Nombre.setBackground(new java.awt.Color(5, 86, 172));
                    apellidos.setEditable(false);
                    apellidos.setBackground(new java.awt.Color(5, 86, 172));
                    ID.setEditable(false);
                    ID.setBackground(new java.awt.Color(5, 86, 172));
                    puesto.setEnabled(false);
                    puesto.setBackground(new java.awt.Color(5, 86, 172));
                    puesto.setVisible(false);
                    puestoText.setVisible(true);

                    fondoGuardar.setVisible(false);
                    btnGuardar.setVisible(false);
                    btnGuardarPassword.setVisible(false);

                    cambiarContrasena.setVisible(false);
                    contrasena.setVisible(false);
                    textContrasena.setVisible(false);
                    confirmarContrasena.setVisible(false);
                    textCofirmarContrasena.setVisible(false);
                    cambiarContrasena.setSelected(false);

                    actualizarDatosContrasenia();
                    mostrarDatos();

                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Alerta", JOptionPane.WARNING_MESSAGE);
            }

        }


    }//GEN-LAST:event_btnGuardarPasswordMouseClicked

    private void btnBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBusquedaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBusquedaKeyTyped

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        mostrarDatos();
    }//GEN-LAST:event_formWindowGainedFocus

    private void barraBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraBusquedaKeyTyped

    }//GEN-LAST:event_barraBusquedaKeyTyped

    private void barraBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraBusquedaKeyReleased
        filtrarDatos(barraBusqueda.getText());
    }//GEN-LAST:event_barraBusquedaKeyReleased

    private void barraBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraBusquedaActionPerformed

    private void barraBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraBusquedaMouseClicked
        barraBusqueda.setText("");
    }//GEN-LAST:event_barraBusquedaMouseClicked

    private void btnVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseClicked
                reportes ventanaReportes = null;
        try {
            ventanaReportes = new reportes();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ventanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventanaReportes.setVisible(true);
    }//GEN-LAST:event_btnVentasMouseClicked

    public void mostrarDatos() {

        String[] titulos = {"ID Usuario", "Nombre", "Apellidos", "Puesto"};
        String[] registros = new String[5];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String SQL = "select * from user";

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            while (rs.next()) {

                registros[0] = rs.getString("idUser");
                registros[1] = rs.getString("Nombre");
                registros[2] = rs.getString("apellidos");
                registros[3] = rs.getString("puesto");

                modelo.addRow(registros);

            }

            tablaUsuarios.setModel(modelo);
            tablaUsuarios.setDefaultEditor(Object.class, null);

        } catch (Exception e) {
            System.out.println("Error" + e);

        }

    }

    public void actualizarDatos() {

        try {
            String SQL = "update user set Nombre=?,apellidos=?,puesto=? where iduser=?";
            PreparedStatement pst = con.prepareStatement(SQL);
            String idSeleccionada = tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 0).toString();
            pst.setString(1, Nombre.getText());
            pst.setString(2, apellidos.getText());
            int seleccionPuesto = puesto.getSelectedIndex();
            pst.setString(3, puesto.getItemAt(seleccionPuesto));
            pst.setString(4, idSeleccionada);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Cambios guardados correctamente");

        } catch (Exception e) {
            System.out.println("Error" + e);
        }

    }

    public void actualizarDatosContrasenia() {

        try {
            String SQL = "update user set Nombre=?,apellidos=?,puesto=?,password=? where iduser=?";
            PreparedStatement pst = con.prepareStatement(SQL);
            String idSeleccionada = tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 0).toString();
            pst.setString(1, Nombre.getText());
            pst.setString(2, apellidos.getText());
            int seleccionPuesto = puesto.getSelectedIndex();
            pst.setString(3, puesto.getItemAt(seleccionPuesto));
            String pass = String.valueOf(contrasena.getPassword());
            pst.setString(4, pass);
            pst.setString(5, idSeleccionada);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Cambios guardados correctamente");

        } catch (Exception e) {
            System.out.println("Error" + e);
        }

    }
    
     public void filtrarDatos(String Valor) {

        String[] titulos = {"ID Usuario", "Nombre", "Apellidos", "Puesto"};
        String[] registros = new String[5];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String SQL = "select * from user where nombre like '%"+Valor+"%'";

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            while (rs.next()) {

                registros[0] = rs.getString("idUser");
                registros[1] = rs.getString("Nombre");
                registros[2] = rs.getString("apellidos");
                registros[3] = rs.getString("puesto");

                modelo.addRow(registros);

            }

            tablaUsuarios.setModel(modelo);
            tablaUsuarios.setDefaultEditor(Object.class, null);

        } catch (Exception e) {
            System.out.println("Error" + e);

        }
        
        // Buscar apellido 
         String SQL2 = "select * from user where apellidos like '%"+Valor+"%'";

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL2);

            while (rs.next()) {

                registros[0] = rs.getString("idUser");
                registros[1] = rs.getString("Nombre");
                registros[2] = rs.getString("apellidos");
                registros[3] = rs.getString("puesto");

                modelo.addRow(registros);

            }

            tablaUsuarios.setModel(modelo);
            tablaUsuarios.setDefaultEditor(Object.class, null);

        } catch (Exception e) {
            System.out.println("Error" + e);

        }
        

    }

    /**
     * @param args the command line arguments
     */
    public static void ventanaUsuarios() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(inicioAdminmensajeBienvenidass.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField apellidos;
    private javax.swing.JTextField barraBusqueda;
    private javax.swing.JLabel btnArticulos;
    private javax.swing.JLabel btnArticulosFondo;
    private javax.swing.JLabel btnBusqueda;
    private javax.swing.JLabel btnCerrarSesion;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnGuardarPassword;
    private javax.swing.JLabel btnUsuarios;
    private javax.swing.JLabel btnUsuariosFondo;
    private javax.swing.JLabel btnVentas;
    private javax.swing.JLabel btnVentasFondo;
    private javax.swing.JCheckBox cambiarContrasena;
    private javax.swing.JPasswordField confirmarContrasena;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JLabel fondoBarraBusqueda;
    private javax.swing.JLabel fondoBlanco;
    private javax.swing.JLabel fondoCerrarSesion;
    private javax.swing.JLabel fondoEditar;
    private javax.swing.JLabel fondoGuardar;
    private javax.swing.JLabel fondoImgUsuario;
    private javax.swing.JLabel imgCuadroAzul;
    private javax.swing.JLabel imgLogoSeguricam;
    private javax.swing.JLabel imgUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensajeBienvenida;
    private javax.swing.JComboBox<String> puesto;
    private javax.swing.JTextField puestoText;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JLabel textCofirmarContrasena;
    private javax.swing.JLabel textContrasena;
    private javax.swing.JLabel textID;
    private javax.swing.JLabel textPuesto;
    private javax.swing.JLabel txtApellidos;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
