/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StockMaster;

import conexionesSQL.conexionSQL;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static StockMaster.login.nombreUsuario;

/**
 *
 * @author Aleja
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();
    login datosUsuario = new login();
    String txtDescripcion1 = ".";
    public static String IDArticulo;
    public static String[][] Arreglo;
    String[][] ArregloAux;
    public static int numeroArticulos = 0;

    /**
     * Creates new form inicioAdministrador
     */
    public ventanaPrincipal() {
        initComponents();
        mostrarDatos();

    }

    public static String getIDArticulo() {
        return IDArticulo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaArticulos = new javax.swing.JTable();
        Articulo = new javax.swing.JTextField();
        txtArticulo = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        txtID = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        txtCantidadStock = new javax.swing.JLabel();
        precioPublico = new javax.swing.JTextField();
        txtPrecioPublico = new javax.swing.JLabel();
        precioDistribuidor = new javax.swing.JTextField();
        txtPrecioDistribuidor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        txtDescripcion = new javax.swing.JLabel();
        btnBusqueda = new javax.swing.JLabel();
        barraBusqueda = new javax.swing.JTextField();
        fondoBarraBusqueda = new javax.swing.JLabel();
        imgArticulo = new javax.swing.JLabel();
        fondoImgArticulo = new javax.swing.JLabel();
        btnVender = new javax.swing.JLabel();
        fondoVender = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        fondoEditar = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        fondoGuardar = new javax.swing.JLabel();
        imgCuadroAzul = new javax.swing.JLabel();
        imgLogoSeguricam = new javax.swing.JLabel();
        mensajeBienvenida = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JLabel();
        btnUsuariosFondo = new javax.swing.JLabel();
        btnReportes = new javax.swing.JLabel();
        btnReportesFondo = new javax.swing.JLabel();
        btnArticulos = new javax.swing.JLabel();
        btnArticulosFondo = new javax.swing.JLabel();
        fondoBlanco = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();
        fondoCerrarSesion = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(942, 650));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1170, 630));
        jPanel1.setMinimumSize(new java.awt.Dimension(1170, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1170, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablaArticulos.getTableHeader().setReorderingAllowed(false);
        tablaArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaArticulosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaArticulos);
        if (tablaArticulos.getColumnModel().getColumnCount() > 0) {
            tablaArticulos.getColumnModel().getColumn(1).setMinWidth(200);
            tablaArticulos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tablaArticulos.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 560, -1));

        Articulo.setEditable(false);
        Articulo.setBackground(new java.awt.Color(5, 86, 172));
        Articulo.setForeground(new java.awt.Color(51, 51, 51));
        Articulo.setBorder(null);
        Articulo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(Articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 170, 20));

        txtArticulo.setForeground(new java.awt.Color(255, 255, 255));
        txtArticulo.setText("Articulo:");
        jPanel1.add(txtArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, -1));

        Id.setEditable(false);
        Id.setBackground(new java.awt.Color(5, 86, 172));
        Id.setForeground(new java.awt.Color(51, 51, 51));
        Id.setToolTipText("La ID no se puede modificar");
        Id.setBorder(null);
        Id.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 170, 20));

        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setText("ID:");
        txtID.setToolTipText("La ID no se puede modificar");
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, -1));

        stock.setEditable(false);
        stock.setBackground(new java.awt.Color(5, 86, 172));
        stock.setForeground(new java.awt.Color(51, 51, 51));
        stock.setBorder(null);
        stock.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 170, 20));

        txtCantidadStock.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidadStock.setText("Stock:");
        jPanel1.add(txtCantidadStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        precioPublico.setEditable(false);
        precioPublico.setBackground(new java.awt.Color(5, 86, 172));
        precioPublico.setForeground(new java.awt.Color(51, 51, 51));
        precioPublico.setBorder(null);
        precioPublico.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(precioPublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 140, 20));

        txtPrecioPublico.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioPublico.setText("Precio Publico:");
        jPanel1.add(txtPrecioPublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));

        precioDistribuidor.setEditable(false);
        precioDistribuidor.setBackground(new java.awt.Color(5, 86, 172));
        precioDistribuidor.setForeground(new java.awt.Color(51, 51, 51));
        precioDistribuidor.setBorder(null);
        precioDistribuidor.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jPanel1.add(precioDistribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 120, 20));

        txtPrecioDistribuidor.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioDistribuidor.setText("Precio Distribuidor:");
        jPanel1.add(txtPrecioDistribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));

        jScrollPane1.setEnabled(false);

        descripcion.setEditable(false);
        descripcion.setColumns(20);
        descripcion.setForeground(new java.awt.Color(51, 51, 51));
        descripcion.setRows(5);
        descripcion.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(descripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 270, 110));

        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setText("Descripción:");
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, -1, -1));

        btnBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-search-more-96.png"))); // NOI18N
        btnBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBusquedaMouseClicked(evt);
            }
        });
        jPanel1.add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 95, -1, -1));

        barraBusqueda.setBackground(new java.awt.Color(162, 162, 162));
        barraBusqueda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        barraBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        barraBusqueda.setText("Búsqueda de articulo: ");
        barraBusqueda.setToolTipText("Búsqueda basada en nombre y descripción de artículos");
        barraBusqueda.setBorder(null);
        barraBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraBusquedaMouseClicked(evt);
            }
        });
        barraBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barraBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                barraBusquedaKeyTyped(evt);
            }
        });
        jPanel1.add(barraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 340, 30));

        fondoBarraBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barrabusqueda2.png"))); // NOI18N
        jPanel1.add(fondoBarraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        imgArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-full-image-96.png"))); // NOI18N
        jPanel1.add(imgArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        fondoImgArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rectángulo 12.png"))); // NOI18N
        jPanel1.add(fondoImgArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, -1, -1));

        btnVender.setForeground(new java.awt.Color(255, 255, 255));
        btnVender.setText("Vender");
        btnVender.setToolTipText("Vender el artículo seleccionado");
        btnVender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVenderMouseClicked(evt);
            }
        });
        jPanel1.add(btnVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 556, -1, -1));

        fondoVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rectángulo 11.png"))); // NOI18N
        fondoVender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(fondoVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 553, -1, -1));

        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Modificar los datos del artículo seleccionado");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 556, -1, -1));

        fondoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rectángulo -1.png"))); // NOI18N
        jPanel1.add(fondoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 553, -1, -1));

        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar cambios");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 556, -1, -1));

        fondoGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rectángulo -1c.png"))); // NOI18N
        jPanel1.add(fondoGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 553, -1, -1));

        imgCuadroAzul.setBackground(new java.awt.Color(5, 86, 172));
        imgCuadroAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rectángulo 9b.png"))); // NOI18N
        jPanel1.add(imgCuadroAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        imgLogoSeguricam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopeque.png"))); // NOI18N
        imgLogoSeguricam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgLogoSeguricamMouseClicked(evt);
            }
        });
        jPanel1.add(imgLogoSeguricam, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        mensajeBienvenida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mensajeBienvenida.setForeground(new java.awt.Color(102, 102, 102));
        mensajeBienvenida.setText("Te damos la bienvendida + nombreUsuario");
        jPanel1.add(mensajeBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 370, 30));

        btnUsuarios.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setToolTipText("Alta y modificación de usuarios");
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
        });
        jPanel1.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 88, 70, 30));

        btnUsuariosFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RectánguloAzulClaropeque.png"))); // NOI18N
        jPanel1.add(btnUsuariosFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        btnReportes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");
        btnReportes.setToolTipText("Generar reportes de ventas y artículos");
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesMouseClicked(evt);
            }
        });
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 88, 70, 30));

        btnReportesFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RectánguloAzulClaropeque.png"))); // NOI18N
        jPanel1.add(btnReportesFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        btnArticulos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnArticulos.setForeground(new java.awt.Color(255, 255, 255));
        btnArticulos.setText("Añadir artículo");
        btnArticulos.setToolTipText("Dar de alta un artículo.");
        btnArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArticulosMouseClicked(evt);
            }
        });
        jPanel1.add(btnArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 88, 100, 30));

        btnArticulosFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RectánguloAzulpeque.png"))); // NOI18N
        jPanel1.add(btnArticulosFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        fondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RectanguloBlanco3.png"))); // NOI18N
        jPanel1.add(fondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 870, -1));

        btnCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setToolTipText("Finalizar sesión");
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 585, -1, 20));

        fondoCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Grupo 22.png"))); // NOI18N
        jPanel1.add(fondoCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, -1, -1));

        btnCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-shopping-cart-48.png"))); // NOI18N
        btnCarrito.setToolTipText("Ver carrito de compra");
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarritoMouseClicked(evt);
            }
        });
        jPanel1.add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barraBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraBusquedaMouseClicked
        barraBusqueda.setText("");
    }//GEN-LAST:event_barraBusquedaMouseClicked

    private void barraBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraBusquedaKeyTyped


    }//GEN-LAST:event_barraBusquedaKeyTyped

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        int result = JOptionPane.showConfirmDialog(null, " ¿Está seguro que desea cerrar la sesión? ", "",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            //System.exit(0);
            login ventanaLogin = new login();
            this.dispose();
            ventanaLogin.setVisible(true);

        }
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        imgLogoSeguricam.requestFocus();
        fondoGuardar.setVisible(false);
        btnGuardar.setVisible(false);
        mensajeBienvenida.setText("Te damos la bienvenida, " + datosUsuario.getNombreUsuario() + " " + datosUsuario.getApellidosUsuario());
        String puesto = datosUsuario.getpuesto().toUpperCase();

        if (puesto.equals("EMPLEADO")) {
            btnUsuarios.setVisible(false);
            btnUsuariosFondo.setVisible(false);
            btnEditar.setVisible(false);
            fondoEditar.setVisible(false);
        } else {
            btnUsuarios.setVisible(true);
            btnUsuariosFondo.setVisible(true);
            btnEditar.setVisible(true);
            fondoEditar.setVisible(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        Articulo.setEditable(true);
        Articulo.setBackground(Color.WHITE);
        stock.setEditable(true);
        stock.setBackground(Color.WHITE);
        precioDistribuidor.setEditable(true);
        precioDistribuidor.setBackground(Color.WHITE);
        precioPublico.setEditable(true);
        precioPublico.setBackground(Color.WHITE);
        descripcion.setEditable(true);
        fondoGuardar.setVisible(true);
        btnGuardar.setVisible(true);

    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        int result = JOptionPane.showConfirmDialog(null, " ¿Está seguro que desea realizar los cambios? ", "",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            actualizarDatos();
            mostrarDatos();
            JOptionPane.showMessageDialog(null, "Cambios guardados correctamente");
            Articulo.setEditable(false);
            Articulo.setBackground(new java.awt.Color(5, 86, 172));
            Id.setEditable(false);
            Id.setBackground(new java.awt.Color(5, 86, 172));
            stock.setEditable(false);
            stock.setBackground(new java.awt.Color(5, 86, 172));
            precioDistribuidor.setEditable(false);
            precioDistribuidor.setBackground(new java.awt.Color(5, 86, 172));
            precioPublico.setEditable(false);
            precioPublico.setBackground(new java.awt.Color(5, 86, 172));
            descripcion.setEditable(false);
            fondoGuardar.setVisible(false);
            btnGuardar.setVisible(false);

        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        ventanaUsuarios ventanaUser = new ventanaUsuarios();
        ventanaUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void tablaArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaArticulosMouseClicked
        Id.setText(tablaArticulos.getValueAt(tablaArticulos.getSelectedRow(), 0).toString());
        Articulo.setText(tablaArticulos.getValueAt(tablaArticulos.getSelectedRow(), 1).toString());
        precioPublico.setText(tablaArticulos.getValueAt(tablaArticulos.getSelectedRow(), 2).toString());
        precioDistribuidor.setText(tablaArticulos.getValueAt(tablaArticulos.getSelectedRow(), 3).toString());
        stock.setText(tablaArticulos.getValueAt(tablaArticulos.getSelectedRow(), 4).toString());
        mostrarDatos2(tablaArticulos.getValueAt(tablaArticulos.getSelectedRow(), 0).toString());
        descripcion.setText(txtDescripcion1);
    }//GEN-LAST:event_tablaArticulosMouseClicked

    private void btnArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArticulosMouseClicked
        altaArticulos ventanaAltaArticulos = new altaArticulos();
        ventanaAltaArticulos.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnArticulosMouseClicked

    private void barraBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraBusquedaKeyReleased
        filtrarDatos(barraBusqueda.getText());
    }//GEN-LAST:event_barraBusquedaKeyReleased

    private void btnVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVenderMouseClicked
        if (Articulo.getText().equals("") | stock.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Tienes que seleccionar un artículo valido");
        } else {
            IDArticulo = Id.getText();
            tipoDeVenta ventanaVenta = new tipoDeVenta();
            ventanaVenta.setVisible(true);
        }
    }//GEN-LAST:event_btnVenderMouseClicked

    private void imgLogoSeguricamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLogoSeguricamMouseClicked


    }//GEN-LAST:event_imgLogoSeguricamMouseClicked

    private void btnCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarritoMouseClicked
        carritoVentas ventanaCarrito = new carritoVentas();
        ventanaCarrito.setVisible(true);
    }//GEN-LAST:event_btnCarritoMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        mostrarDatos();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusquedaMouseClicked
        filtrarDatos(barraBusqueda.getText());
    }//GEN-LAST:event_btnBusquedaMouseClicked

    private void btnReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseClicked
        reportes ventanaReportes = null;
        try {
            ventanaReportes = new reportes();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ventanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventanaReportes.setVisible(true);
    }//GEN-LAST:event_btnReportesMouseClicked

    public void mostrarDatos() {

        String[] titulos = {"ID", "Articulo", "P. Publico", "P. Distribuidor", "Stock"};
        String[] registros = new String[5];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        
        String SQL = "select * from item";

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            while (rs.next()) {

                registros[0] = rs.getString("iditem");
                registros[1] = rs.getString("nombre");
                registros[2] = rs.getString("precio_publico");
                registros[3] = rs.getString("precio_distribuidor");
                registros[4] = rs.getString("stock");

                modelo.addRow(registros);

            }

            tablaArticulos.setModel(modelo);           
            tablaArticulos.setDefaultEditor(Object.class, null);
            establecerColumnas();
        } catch (Exception e) {
            System.out.println("Error" + e);

        }

    }

    public void establecerColumnas(){
    
            tablaArticulos.getColumnModel().getColumn(0).setPreferredWidth(25);
            tablaArticulos.getColumnModel().getColumn(1).setPreferredWidth(350);
            tablaArticulos.getColumnModel().getColumn(2).setPreferredWidth(50);
            tablaArticulos.getColumnModel().getColumn(3).setPreferredWidth(50);
            tablaArticulos.getColumnModel().getColumn(4).setPreferredWidth(25);
    }
    
    public void filtrarDatos(String Valor) {

        String[] titulos = {"ID", "Articulo", "P. Publico", "P. Distribuidor", "Stock"};
        String[] registros = new String[5];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String SQL = "select * from item where descripcion like '%" + Valor + "%'";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);


            while (rs.next()) {

                registros[0] = rs.getString("iditem");
                registros[1] = rs.getString("nombre");
                registros[2] = rs.getString("precio_publico");
                registros[3] = rs.getString("precio_distribuidor");
                registros[4] = rs.getString("stock");
                modelo.addRow(registros);

            }

            tablaArticulos.setModel(modelo);
            tablaArticulos.setDefaultEditor(Object.class, null);
            establecerColumnas();

        } catch (Exception e) {
            System.out.println("Error" + e);

        }

    }

    public void mostrarDatos2(String identificador) {

        String SQL = "select * from item where iditem = '" + identificador + "'";

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            while (rs.next()) {
                txtDescripcion1 = rs.getString("descripcion");
            }

        } catch (Exception e) {
            System.out.println("Error" + e);

        }

    }

    public void actualizarDatos() {

        try {
            String SQL = "update item set nombre=?,descripcion=?,precio_publico=?, precio_distribuidor=?, stock=? where iditem=?";
            PreparedStatement pst = con.prepareStatement(SQL);
            String idSeleccionada = tablaArticulos.getValueAt(tablaArticulos.getSelectedRow(), 0).toString();
            pst.setString(1, Articulo.getText());
            pst.setString(2, descripcion.getText());
            pst.setFloat(3, Float.parseFloat(precioPublico.getText()));
            pst.setFloat(4, Float.parseFloat(precioDistribuidor.getText()));
            pst.setInt(5, Integer.parseInt(stock.getText()));
            pst.setString(6, idSeleccionada);

            pst.execute();
            JOptionPane.showMessageDialog(null, "Cambios guardados correctamente");

        } catch (Exception e) {
            System.out.println("Error" + e);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void ventanaPrincipal() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(inicioAdminmensajeBienvenidass.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Articulo;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField barraBusqueda;
    private javax.swing.JLabel btnArticulos;
    private javax.swing.JLabel btnArticulosFondo;
    private javax.swing.JLabel btnBusqueda;
    private javax.swing.JLabel btnCarrito;
    private javax.swing.JLabel btnCerrarSesion;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnReportes;
    private javax.swing.JLabel btnReportesFondo;
    private javax.swing.JLabel btnUsuarios;
    private javax.swing.JLabel btnUsuariosFondo;
    private javax.swing.JLabel btnVender;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel fondoBarraBusqueda;
    private javax.swing.JLabel fondoBlanco;
    private javax.swing.JLabel fondoCerrarSesion;
    private javax.swing.JLabel fondoEditar;
    private javax.swing.JLabel fondoGuardar;
    private javax.swing.JLabel fondoImgArticulo;
    private javax.swing.JLabel fondoVender;
    private javax.swing.JLabel imgArticulo;
    private javax.swing.JLabel imgCuadroAzul;
    private javax.swing.JLabel imgLogoSeguricam;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mensajeBienvenida;
    private javax.swing.JTextField precioDistribuidor;
    private javax.swing.JTextField precioPublico;
    private javax.swing.JTextField stock;
    private javax.swing.JTable tablaArticulos;
    private javax.swing.JLabel txtArticulo;
    private javax.swing.JLabel txtCantidadStock;
    private javax.swing.JLabel txtDescripcion;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtPrecioDistribuidor;
    private javax.swing.JLabel txtPrecioPublico;
    // End of variables declaration//GEN-END:variables
}
